version: 2.1
parameters:
      ADMIN_URL:
        type: string
        default: 'ADMIN_URL'

      # CLIENT_URL:
      #   type: string
      #   default: 'CLIENT_URL'

      # LENDER_URL:
      #   type: string
      #   default: 'LENDER_URL'

      # VENDOR_URL:
      #   type: string
      #   default: 'VENDOR_URL'

jobs:
  job-param:
    

    machine: true
    
    steps:
      - checkout
      - run: |
          echo <<parameters.ADMIN_URL>>  
        
         
workflows:
  build:
    jobs:
      - job-param
   # echo <<parameters.CLIENT_URL>>
          # echo <<parameters.LENDER_URL>>
          # echo <<parameters.VENDOR_URL>>         