version: 2.1
parameters:
      ADMIN_URL:
        type: string
        

      CLIENT_URL:
        type: string
        

      LENDER_URL:
        type: string
        

      VENDOR_URL:
        type: string
        

jobs:
  job-param:
    

    machine: true
    
    steps:
      - checkout
      - run: |
          echo <<pipeline.parameters.ADMIN_URL>>  
          echo <<pipeline.parameters.CLIENT_URL>>
          echo <<pipeline.parameters.LENDER_URL>>
          echo <<pipeline.parameters.VENDOR_URL>>
         
workflows:
  build:
    jobs:
      - job-param
            