version: 2.1


jobs:
  job-param:
    

    machine: true
    parameters:
      ADMIN_URL:
        type: string
        default: 'ADMIN_URL'

      CLIENT_URL:
        type: string
        default: 'CLIENT_URL'

      LENDER_URL:
        type: string
        default: 'LENDER_URL'

      VENDOR_URL:
        type: string
        default: 'VENDOR_URL'
    steps:
      - checkout
      - run: echo <<parameters.ADMIN_URL>>
          
      - run: echo <<parameters.CLIENT_URL>>
      - run: echo <<parameters.LENDER_URL>>
      - run: echo <<parameters.VENDOR_URL>>    
workflows:
  build:
    jobs:
      - job-param 
    