version: 2.1
jobs:
  build:
    parameters:
      p:
        type: integer
        default: 2
    parallelism: << parameters.p >>
    machine: true
    steps:
      - checkout
      - run : echo << parameters.p >>
workflows:
  workflow:
    jobs:
      - build