
version: 2.0
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

      - run:
          
          name: Trigger docker remotely
          command: |  
            curl --location --request POST  -u ${CIRCLE_API_USER_TOKEN}  https://circleci.com/api/v1.1/project/github/Nurmukhamed02/trigger-circleci/tree/main
workflow:
  jobs:
    - build
